name: versaoPromotores
description: Aplicativo para gestÃ£o de promotores de vendas

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flippo_navigation: ^0.0.6
  mask_text_input_formatter: ^1.0.7
  cpf_cnpj_validator: ^1.0.5
  keyboard_actions: ^3.3.0+12
  brasil_fields: ^0.2.0
  http:
  flutter_date_pickers:
  google_map_polyline:
  maps_toolkit: ^1.0.1+3
  flushbar: ^1.10.4
  checkbox_formfield: ^0.1.0+3
  google_maps_utils:
  geolocator: ^5.3.1
  cloud_functions: ^0.1.0
  location: ^2.3.5
  carousel_pro: ^1.0.0
  carousel_slider: ^2.0.0
  date_format:
  pdf: ^1.8.1
  giffy_dialog:
  flare_flutter: ^2.0.3
  cloud_firestore: ^0.11.0
  scoped_model: ^1.0.1
  firebase_auth: ^0.15.3
  firebase_messaging:
  flutter_animated_dialog: ^1.1.0
  nice_button:
  firebase_core:
  grouped_buttons:
  rxdart: ^0.20.0
  font_awesome_flutter: ^8.0.1
  flutter_local_notifications:
  geocoder:
  image_picker: ^0.6.0+17
  firebase_storage:
  image_cropper: ^1.2.1
  path_provider: ^1.6.7
  date_range_picker: ^1.0.5
  syncfusion_flutter_datepicker:
  url_launcher: ^5.1.1
  dio: ^3.0.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:

    - family: QuickSand
      fonts:
        - asset: fonts/quicksand-bold.ttf

    - family: QuickSandRegular
      fonts:
        - asset: fonts/Quicksand_Regular.ttf

    - family: Roboto-Light
      fonts:
        - asset: fonts/Roboto-Bold.ttf

    - family: Helvetica
      fonts:
        - asset: fonts/HelveticaNeue-Regular.ttf

    - family: RobotoBold
      fonts:
        - asset: fonts/Roboto-Bold.ttf



  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
